# 1. 플랫폼 지정 (M1/M2 대비)
FROM --platform=linux/amd64 node:20

ENV NODE_OPTIONS=--max-old-space-size=2048

# 작업 디렉토리 설정
WORKDIR /app

# 2. 의존성 설치
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 3. 빌드 시점 ARG 정의
ARG NEXT_PUBLIC_SERVER_HOST
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY
ARG NEXT_PUBLIC_DISCORD_SERVER
ARG NEXT_PUBLIC_DISCORD_CHANNEL

# 4. ARG → ENV 반영
ENV NEXT_PUBLIC_SERVER_HOST=$NEXT_PUBLIC_SERVER_HOST
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS=$NEXT_PUBLIC_GOOGLE_ANALYTICS
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=$NEXT_PUBLIC_FIREBASE_VAPID_KEY
ENV NEXT_PUBLIC_DISCORD_SERVER=$NEXT_PUBLIC_DISCORD_SERVER
ENV NEXT_PUBLIC_DISCORD_CHANNEL=$NEXT_PUBLIC_DISCORD_CHANNEL

# 5. 소스 복사 및 빌드
COPY . .
RUN yarn build

# 6. 포트 오픈 & 실행
EXPOSE 4000
CMD ["yarn", "start"]
