export enum BadgeCategory {
  ATTENDANCE = "ATTENDANCE",
  COMMUNITY = "COMMUNITY",
  GUILD_SCRIM = "GUILD_SCRIM",
  CHAMPION = "CHAMPION",
  SPECIAL = "SPECIAL",
}

export enum BadgeCode {
  // 출석 카테고리
  FIRST_STEP = "FIRST_STEP",
  STEADY_START = "STEADY_START",
  MONTHLY_PERFECT = "MONTHLY_PERFECT",
  ATTENDANCE_KING = "ATTENDANCE_KING",
  LEGENDARY_ATTENDANCE = "LEGENDARY_ATTENDANCE",

  // 커뮤니티 카테고리
  FIRST_POST = "FIRST_POST",
  CHATTERBOX = "CHATTERBOX",
  POPULAR = "POPULAR",
  COMMUNITY_ACTIVIST = "COMMUNITY_ACTIVIST",
  LIKE_MASTER = "LIKE_MASTER",

  // 길드/스크림 카테고리
  GUILD_BEGINNER = "GUILD_BEGINNER",
  FIRST_WIN = "FIRST_WIN",
  TEN_WINS = "TEN_WINS",
  WIN_STREAK_KING = "WIN_STREAK_KING",
  VETERAN = "VETERAN",

  // 챔피언 카테고리
  ONE_TRICK = "ONE_TRICK",
  MASTER_PATH = "MASTER_PATH",
  WINRATE_MASTER = "WINRATE_MASTER",
  KDA_MASTER = "KDA_MASTER",

  // 기타/특별
  EARLY_ADOPTER = "EARLY_ADOPTER",
  RICH = "RICH",
  GUILD_MASTER = "GUILD_MASTER",
}
